FROM alpine:latest
RUN apk --update add postgresql-client
RUN apk add bash
RUN apk -v --update add \
        python \
        py-pip \
        groff \
        less \
        mailcap \
        && \
    pip install --upgrade awscli python-magic && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*
CMD ["/bin/bash"]
